class Avatars {
  final List<String> maleAvatars = [
    'assets/images/avatars/ahmed.png',
    'assets/images/avatars/anesu.png',
    'assets/images/avatars/bryan.png',
    'assets/images/avatars/mikee.png',
    'assets/images/avatars/pete.png',
    'assets/images/avatars/singh.png',
    'assets/images/avatars/hamza.png',
    'assets/images/avatars/ivan.png',
    'assets/images/avatars/kaito.png',
    'assets/images/avatars/obi.png',
    'assets/images/avatars/pierr.png',
    'assets/images/avatars/tyler.png',
    'assets/images/avatars/yeshua.png',
    'assets/images/avatars/andy.png',
    'assets/images/avatars/brad.png',
    'assets/images/avatars/juan.png',
    'assets/images/avatars/paul.png',
    'assets/images/avatars/sheik.png',
    'assets/images/avatars/vladmir.png',
  ];
  final List<String> femaleAvatars = [
    'assets/images/avatars/divya.png',
    'assets/images/avatars/grace.png',
    'assets/images/avatars/ivana.png',
    'assets/images/avatars/julia.png',
    'assets/images/avatars/layla.png',
    'assets/images/avatars/liz.png',
    'assets/images/avatars/ruth.png',
    'assets/images/avatars/yael.png',
    'assets/images/avatars/alina.png',
    'assets/images/avatars/ava.png',
    'assets/images/avatars/denpa.png',
    'assets/images/avatars/emi.png',
    'assets/images/avatars/leila.png',
    'assets/images/avatars/madison.png',
    'assets/images/avatars/sara.png',
    'assets/images/avatars/diane.png',
    'assets/images/avatars/fatuma.png',
    'assets/images/avatars/isabella.png',
    'assets/images/avatars/kyia.png',
    'assets/images/avatars/liu.png',
    'assets/images/avatars/marinees.png',
    'assets/images/avatars/rehan.png',
  ];
}

List avatars = [];
